### ISSUE TITLE
Cannot find module '@modelcontextprotocol/sdk/types.js

### ISSUE THREAD

**Issue by prachit07** [googleapis/js-genai#684]
Cannot find module '@modelcontextprotocol/sdk/types.js' from 'node_modules/@google/genai/dist/node/index.cjs'

Getting this error after the update to 1.5.0

**Comment by ZeroCho** [comment]
I think even #669 does not fix this issue.
Installing `@modelcontextprotocol/sdk` manually fixed this issue, but as it is stated as **optional** peer dependency in `package.json`, it should be okay even when it isn't installed.

**Comment by shmishra99** [comment]
Hi @prachit07 , 

This issue stems from recent changes that made `@modelcontextprotocol/sdk` dependencies optional. As a workaround, you can manually install it by running `npm i @modelcontextprotocol/sdk`. I'm escalating this issue and will update you shortly.  
Thank You!!

@ZeroCho Thanks for your input.

**Comment by TomFrankly** [comment]
Just chiming in to mention my users hit this issue with a Pipedream component I made that has `import { GoogleGenAI } from "@google/genai"` as a requirement.

I've disabled Gemini for the time being (it's a component that supports several GenAI providers) – I'll eagerly await an update here so I can enable it again!

**Comment by amirh** [comment]
Thanks for reporting.
I'm unable to reproduce this with a simple project that's using `@google/genai` without using MCP, is anyone able to share a minimal project that reproduces the issue?

**Comment by AyushAgrawal-A2** [comment]
@amirh do a production build, this change just breaks all production, dev is running fine

**Comment by amirh** [comment]
Thanks, unfortunately I can't tell how to reproduce your production build, is it a separate tsconfig? is it something that your build tooling is doing?

If someone can provide a simple repro it will still be helpful.

**Comment by AyushAgrawal-A2** [comment]
@amirh 
I think it is just because there is a missing `type` prefix in the import here, dev dependencies will not cause an issue when imported as just `type`, will be removed in transpiling automatically

should be 
```
import type {Tool as McpTool} from '@modelcontextprotocol/sdk/types.js';
```

![Image](https://github.com/user-attachments/assets/8ee5ee58-845f-4ded-b1dd-9843bce2f934)

**Comment by AyushAgrawal-A2** [comment]
this is the error we received when we shipped to prod yesterday, we were using `^1.4.0` version in QA, in Prod because of `^` caret semver  - `1.5.0` got installed and broke the api on release

![Image](https://github.com/user-attachments/assets/18dd6cd0-425a-4388-8579-ff17b3326e11)

**Comment by amirh** [comment]
https://github.com/googleapis/js-genai/pull/687 with the fix

**Comment by amirh** [comment]
Fixed in v1.5.1
